plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
	id 'maven-publish'
}

base {
	archivesName = "lootbeams"
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"lootbeams" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	compileOnly("org.polyfrost.oneconfig:config-impl:1.2.7") {
		transitive = false
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
